insert into PageText (text_id, language, text) values ('1', 'EN-US', 'Element to Class');
insert into PageText (text_id, language, text) values ('2', 'EN-US', 'Element');
insert into PageText (text_id, language, text) values ('3', 'EN-US', 'Class');
insert into PageText (text_id, language, text) values ('4', 'EN-US', 'Move CSS styles off of');
insert into PageText (text_id, language, text) values ('5', 'EN-US', 'elements and into classes');
insert into PageText (text_id, language, text) values ('6', 'EN-US', 'Drag and drop');
insert into PageText (text_id, language, text) values ('7', 'EN-US', 'your CSS file here');
insert into PageText (text_id, language, text) values ('8', 'EN-US', 'or');
insert into PageText (text_id, language, text) values ('9', 'EN-US', 'browse');
insert into PageText (text_id, language, text) values ('10', 'EN-US', 'to begin the upload');
insert into PageText (text_id, language, text) values ('11', 'EN-US', 'Upload File');
insert into PageText (text_id, language, text) values ('12', 'EN-US', 'New CSS File<');
insert into PageText (text_id, language, text) values ('13', 'EN-US', 'Download');
insert into PageText (text_id, language, text) values ('14', 'EN-US', 'Cancel');
